### ISSUE TITLE
REQUEST: Option to open all links in g.e-hentai or exhentai

### ISSUE THREAD

**Issue by ramenchef** [dnsev-h/h-links#2]
This is a request to reinstate the option exlinks had to open all links in the site of your choice.

**Comment by dnsev-h** [comment]
Sure. Let me first ask if you care if there's one option for every type of link?

The reason I took it out was because there were like 6 different options for gallery link, torrent link, archiver link, etc. and that seemed like overkill.

**Comment by ramenchef** [comment]
Just have a catch all imo. maybe a dropdown that lets you select between g.e-hentai, exhentai, or smart links.

**Comment by dnsev-h** [comment]
Exactly what I'm doing. Sounds good.

**Comment by dnsev-h** [comment]
Should be added in [1.0.1](https://github.com/dnsev-h/h-links/commit/ec729ed2ec8d754ef228818cbd737eb810e96ec2)

See if it works for what you wanted.

**Comment by ramenchef** [comment]
Perfect, that's exactly what I had in mind. Thanks!
