### ISSUE TITLE
Bad not working properly on filters

### ISSUE THREAD

**Issue by ribdib** [dnsev-h/h-links#4]
The bad tag isn't working properly with filters. Filtering with bad still pushes those tags up when sorting by filter. From what I understand from reading the comment in the filter function, anything tagged with bad should remove highlights from the entry (including those that aren't tagged bad?). But instead, tags that are flagged bad still contribute to the tag count and push the doujins up the easy list.

I'd also like to request that entries with bad flags are just removed from the easy list view.

Example can be seen here:
https://u.pomf.io/wwukao.webm

Showing count is increased even with bad tags:
https://u.pomf.io/kopbab.webm

**Comment by dnsev-h** [comment]
Thanks, I've fixed the bug and it will be available in the next release.

I'll work on adding an option to hide entries based on their filters.

**Comment by dnsev-h** [comment]
Should be added in [1.1.0](https://github.com/dnsev-h/h-links/tree/v1.1.0)

Let me know if you experience any more problems with it.
